#!/usr/bin/env python
import sys
import thicc.lexer as lexer


if len(sys.argv) < 2:
    print("usage: thicc src.c")
    sys.exit()

with open(sys.argv[1], "r") as f:
    text = f.read()

lex = lexer.Lexer()
toks = lex.tokenize(text)
print(toks)


